blog/account/urls.py
from account import views
from django.conf.urls import include,url,patterns
#blog urls
urlpatterns = patterns('',
	url(r'^register/$',views.register,name='register'),

	)

blog/blog/urls.py
from django.conf.urls import patterns, include, url
from views import *
from django.contrib import admin
from djangoblog.api import ArticleResource
import settings
admin.autodiscover()
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$',iindex),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/',include('account.urls')),
    url(r'^blog/',include('djangoblog.urls',namespace='blog')),
    
    url(r'^api/', include(ArticleResource().urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),    
    url(r'^ckeditor/', include('ckeditor.urls'))  ,
)

blog/djangoblog/urls.py
from djangoblog import views
from django.conf.urls import include,url,patterns
from djangoblog.api import ArticleResource
#from django.conf import settings if settings.DEBUG is False:

urlpatterns = patterns('',
	url(r'^$',views.index,name='home'),
	url(r'^(?P<pk>\d+)/$',views.DetailView.as_view(), name='detail'),
	 )

blog/account/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
	username = models.CharField(max_length=50)
	password = models.CharField(max_length=50)
	email = models.EmailField()

blog/djangoblog/models.py
#coding:utf-8
from django.db import models
from django.db.models import F

#from django.views.generic.list import ListView
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    title =models.CharField(max_length=150)
    content =models.TextField()
    content=RichTextField('正文')
    timestamp =models.DateTimeField()
    like = models.IntegerField()
    age = models.CharField(max_length=150)

    def add_like(self,article_id):
    	article = self.objects.get(like=article_id)
    	article.like = F('like')+1
    	article.save()


    

blog/testq/models.py
from django.db import models

# Create your models here.

blog/account/forms.py
#coding=utf-8
from django import forms
class  UserForm(forms.Form):
	username=forms.CharField(label='用户名',max_length=50)
	password=forms.CharField(label='密码',widget=forms.PasswordInput())
	email=forms.EmailField(label='电子邮箱')

blog/account/views.py
#!coding=utf-8
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from forms import UserForm
from models import Users
#from django.core.context_processors import csrf
from django.template import RequestContext

# Create your views here.
def register(request):
	if request.method=='POST':
		#c={}
		#x`c.update(csrf(request))
		uf = UserForm(request.POST)
		if uf.is_valid():
			#判断并获取表单
			username = uf.cleaned_data['username']
			password = uf.cleaned_data['password']
			email = uf.cleaned_data['email']
			#入库
			user = Users()
			user.username = username
			user.password = password
			user.email = email
			user.save()
			return render_to_response('success.html',{'username':username},context_instance=RequestContext(request))

	else:
		uf = UserForm()
	return render_to_response('register.html',{'uf':uf},context_instance=RequestContext(request))				
def reg_wait():
	pass
def reg_active():	
	pass

blog/blog/views.py
#!coding:utf-8
from django.shortcuts import render_to_response
from django.core.paginator import Paginator,InvalidPage,EmptyPage

from djangoblog.models import *
#from django import template

# Create your views here.
#from django.views.generic.list import

#view of index
def iindex(request):
	article=Article.objects.all()
	PageSize=1
	blogs=Paginator(article,PageSize) 
	page_range=blogs.page_range   
	try:
		 
		page = int(request.GET.get('page',1)) 
	except ValueError:
	    page = 1
	    print page
	try:
	    posts=blogs.page(page)
 	except:
 		posts=blogs.page(blogs.num_pages)    	
	return render_to_response("index/home.html",{"blogs":article,"page_div":posts,"page_range":page_range})
 
	
 

blog/djangoblog/views.py
#!coding:utf-8
from django.shortcuts import render_to_response,render,get_object_or_404
from django.core.paginator import Paginator,InvalidPage,EmptyPage
from django.views import generic
from djangoblog.models import *
#from django import template

# Create your views here.
#from django.views.generic.list import

#view of index
def index(request):
	article=Article.objects.all()
	PageSize=1
	blogs=Paginator(article,PageSize) 
	#列表形式返回分数    ex:一共5分5页 self.page_range   return[1,2,3,4,5]
	page_range=blogs.page_range   
	try:
		#self.GET.get(a,b)  获取RUL请求，如果请求中没有a， 把b赋值给a ,REUTRN URL?a=b
		page = int(request.GET.get('page',1))  
	except ValueError:
	    page = 1
	    print page
	try:
	    posts=blogs.page(page)
 	except:
 		posts=blogs.page(blogs.num_pages)    	
	return render_to_response("temp/index.html",{"blogs":article,"page_div":posts,"page_range":page_range})
			

class DetailView(generic.DetailView):
	model = Article
	template= 'djangoblog/detail.html'






 

blog/testq/views.py
from django.shortcuts import render

# Create your views here.

blog/account/templates/register.html
<!Doctype>
<html>
<head><title>REGISTER</title></head>
<link href="static/reigster.css">
<body>
   <form method="post" enctype="mutipart/form-data">{% csrf_token %}

    {{uf.as_p}}
      <input type="submit" value="ok"/>
   </form>
   
</body>
</html>

blog/account/templates/success.html
<!Doctype>
<html>
<body>
	<head>
	    <meta http-equiv="Content-Type" content="text/html" ;charset="UTF-8">
		<title>success</title>
	</head>
	<div class="warpper">


	<h1>{{username}}<br>注册成功!</h1> 
	</div>
</body>
</html>

blog/djangoblog/templates/djangoblog/article_detail.html
{%extends 'djangoblog/footer.html'%}
{% if article %}
  
   {%block time%}
   {{article.timestamp|date:"Y.m.d  h:i"}}
   {%endblock%}
   {%block title%}<a>{{article.title}}</a>{%endblock%}
   {%block content%}<h6>{{article.content|safe}}</h6>{%endblock%}
   

{% else %}
    <a>文章没找到.</a>
{% endif %}

blog/djangoblog/templates/djangoblog/footer.html
{%extends 'djangoblog/head.html'%}
{%block footer%}
<footer id="blog_foot" class="cf">
  <ul id="foot_links">
    <li><a href="https://http://weibo.com/CGiSmyLove">@WEIBO</a></li>
    <li><a href="mailto:hello@baoziv587.com?subject=Hi,">say hello</a></li>
    <li><a href="http://baoziv587.com" rel="nofollow">baoziv587.com</a></li>
  </ul>
  <figure id="user_foot"><a href="/">@Davegao</a></figure>
  <h5><a href="baoziv587.com/blog">Davegao</a></h5>
</footer>
<footer id="foot">
  <figure id="logo_foot"><a href="https://www.djangoproject.com">POWER by django</a></figure>
</footer><div id="lights">&nbsp;</div>
<!--  script-->
<script src="{{STATIC_URL}}ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
{%endblock%}

blog/djangoblog/templates/djangoblog/head.html
<html lang="en" ><head>
  <meta charset="utf-8">
  <title>gram.</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/blog/main.css">
  <link href="{{STATIC_URL}}ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/zenburn.css" rel="stylesheet">  
  <link href="{{STATIC_URL}}css/blog/detail.css" rel="stylesheet"> 
</head>
<body class="overlord blog loaded overlord_done">
{%block css%}
{%endblock %}
<!-- head#-->
<!-- blogs loop render -->
<section id="container" class="blog user_home">
  <hr class="articlesplit">
  <article id="bTTEsKLGH6b66psAPwbs" class="post">
    <time class="article_time">
    {%block time%}
    {{blog.timestamp|date:"Y.m.d  h:i"}}
    {%endblock%}</time>
    <h1 class="article_title">
    <a href="{%block link%} {%endblock%}">
    {%block title%}
    {{blog.title}}
    {%endblock%}  
    </a></h1>
    <a href="{{url }}" class="content"></a>
    <p>
    {%block content%}
    {{blog.content|safe}}
    {%endblock%}
    </p>
    
  </article>
  

  </article>- 
  </section>
{%block footer%}
{%endblock%}
</body>
</html>

blog/djangoblog/templates/temp/index.html
<html lang="en" ><head>
  <meta charset="utf-8">
  <title>gram.</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="../static/css/blog/main.css">
  <link href="../static/ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/zenburn.css" rel="stylesheet">   
  <link href="../static/css/blog/detail.css" rel="stylesheet"> 
</head>
<body class="overlord blog loaded overlord_done">
<!-- head#-->
<div id="whiteout"></div>
<header id="user_top" class="cf ">
  <figure id="user_logo"><a href="//blog.markfayngersh.com">汪汪汪</a></figure>
  <h2><a href="//blog.markfayngersh.com">汪汪汪</a></h2>
  <h3>Write Python.Javascript,Html <br>programming for fun
</h3>
  <ul id="user_links">
    <li><a href="http://weibo.com/CGisMylove">@微博</a></li>
    <li><a href="mailto:hello@baoziv587.com?subject=hello,gaoxiang">say hi</a></li>
    <li><a href="http://baoziv587.com" >baoziv587.com</a></li>
  </ul>
</header> 
<!-- blogs loop render -->
<section id="container" class="blog user_home">
{%for blog in blogs%}
  <hr class="articlesplit">
  <article id="bTTEsKLGH6b66psAPwbs" class="post">
    <time datetime="2014-03-20" class="article_time">{{blog.timestamp|date:"Y.m.d  h:i"}}</time>
    <h1 class="article_title">
    <a href="{% url 'blog:detail' blog.id %}">
    {{blog.title|title}}  
    </a></h1>
    
    <p>{{blog.content|safe|truncatechars:350}}</p>
    
    <p class="continue_mark"><a href="{% url 'blog:detail' blog.id%}" class="buttonize outline small">Continue reading →</a></p>
  </article>
  {%endfor%}

  </article>- 
  </section>
<footer id="blog_foot" class="cf">
  <ul id="foot_links">
    <li><a href="https://http://weibo.com/CGiSmyLove">@WEIBO</a></li>
    <li><a href="mailto:hello@baoziv587.com?subject=Hi,">say hello</a></li>
    <li><a href="http://baoziv587.com" rel="nofollow">baoziv587.com</a></li>
  </ul>
  <figure id="user_foot"><a href="/">@Davegao</a></figure>
  <h5><a href="baoziv587.com/blog">Davegao</a></h5>
</footer>
<footer id="foot">
  <figure id="logo_foot"><a href="https://www.djangoproject.com">POWER by django</a></figure>
</footer><div id="lights">&nbsp;</div>
<!--  script-->
<script src="../static/ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>

blog/templates/blog.html
<!Doctype html>
<html>
<head>
  <title>{%block title%}Djangoblog{%endblock%}</title>
  <meta charset='UTF-8'>
  <link rel="stylesheet" href="/static/main.css">
</head>
<body>
 {% autoescape off %}
	<h1>a simple blog</h1>
  
	{% block content %}
      <div class="content">
      {% for blog in blogs %}
      
      		<h1>{{blog.title}}</h1>
         
      <div>
          {{blog.content|safe}}
      </div>
         

      {% endfor%}		
      </div>
  {% endblock %}
	{% block footer %}  
    	<p>Thanks for visiting my blog</p>
	{% endblock %}
  {% endautoescape %}

</body>
</html>

blog/templates/browse.html
{% load staticfiles %}
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>CKEDitor | Select an image to embed</title>
        <link rel="stylesheet" href="{% static "admin/css/base.css" %}" type="text/css" />
        <link rel="stylesheet" href="{% static "ckeditor/galleriffic/css/basic.css" %}" type="text/css" />
        <link rel="stylesheet" href="{% static "ckeditor/galleriffic/css/galleriffic-2.css" %}" type="text/css" />
        <script type="text/javascript" src="{% static "ckeditor/galleriffic/js/jquery-1.3.2.js" %}"></script>
        <script type="text/javascript" src="{% static "ckeditor/galleriffic/js/jquery.galleriffic.js" %}"></script>
        <script type="text/javascript" src="{% static "ckeditor/galleriffic/js/jquery.opacityrollover.js" %}"></script>
        <!-- We only want the thunbnails to display when javascript is disabled -->
        <script type="text/javascript">
            document.write('<style>.noscript { display: none; }</style>');
        </script>
    </head>
    <body>
        <div id="page">
            <div id="container" style="width: 880px">
                {% if files %}
                    <h2>Browse for the image you want, then click 'Embed Image' to continue...</h2>
                {% else %}
                    <h2>No images found. Upload images using the 'Image Button' dialog's 'Upload' tab.</h2>
                {% endif %}

                <!-- Start Advanced Gallery Html Containers -->
                <div id="gallery" class="content">
                    <div class="slideshow-container">
                        <div id="loading" class="loader"></div>
                        <div id="slideshow" class="slideshow"></div>
                    </div>
                    <div id="caption" class="caption-container"></div>
                </div>
                <div id="thumbs" class="navigation">
                    <ul class="thumbs noscript">
                        {% for file in files %}
                        <li>
                            <a {% if file.is_image %}class="thumb"{% endif %} href="{{ file.src }}">
                                {% if file.is_image %}
                                    <img src="{{ file.thumb }}" style="max-width: 75px;"/>
                                {% else %}
                                    {{ file.thumb }}
                                {% endif %}
                            </a>
                            <div class="caption">
                                <div class="submit-row">
                                    <input href="{{ file.src }}" class="default embed" type="submit" name="_embed" value="Embed Image" />
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div style="clear: both;"></div>
            </div>
        </div>
        <script type="text/javascript">
            // helper functions
            function getUrlParam(paramName) {
                var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i') ;
                var match = window.location.search.match(reParam) ;
 
                return (match && match.length > 1) ? match[1] : '' ;
            }
            function scale_image() {
                var max_width = 500;
                var image = $(".advance-link > img");
                var image_width = image.width();
                if (image_width > max_width) {
                    var aspect = image.height() / image_width;
                    var image_height = max_width * aspect;
                    image.width(max_width);
                    image.height(image_height);
                }
            }

            // embedder
            $('.embed').live('click', function() {
                var funcNum = getUrlParam('CKEditorFuncNum');
                var fileUrl = $(this).attr('href');
                window.opener.CKEDITOR.tools.callFunction(funcNum, fileUrl);
                window.close();
            });

            // galleriffic
            jQuery(document).ready(function($) {
                // We only want these styles applied when javascript is enabled
                $('div.navigation').css({'width' : '300px', 'float' : 'left'});
                $('div.content').css('display', 'block');

                // Initially set opacity on thumbs and add
                // additional styling for hover effect on thumbs
                var onMouseOutOpacity = 0.67;
                $('#thumbs ul.thumbs li').opacityrollover({
                    mouseOutOpacity:   onMouseOutOpacity,
                    mouseOverOpacity:  1.0,
                    fadeSpeed:         'fast',
                    exemptionSelector: '.selected'
                });
            
                // Initialize Advanced Galleriffic Gallery
                var gallery = $('#thumbs').galleriffic({
                    delay:                     2500,
                    numThumbs:                 15,
                    preloadAhead:              10,
                    enableTopPager:            true,
                    enableBottomPager:         true,
                    maxPagesToShow:            7,
                    imageContainerSel:         '#slideshow',
                    controlsContainerSel:      '#controls',
                    captionContainerSel:       '#caption',
                    loadingContainerSel:       '#loading',
                    renderSSControls:          true,
                    renderNavControls:         true,
                    playLinkText:              'Play Slideshow',
                    pauseLinkText:             'Pause Slideshow',
                    prevLinkText:              '&lsaquo; Previous Photo',
                    nextLinkText:              'Next Photo &rsaquo;',
                    nextPageLinkText:          'Next &rsaquo;',
                    prevPageLinkText:          '&lsaquo; Prev',
                    enableHistory:             false,
                    autoStart:                 false,
                    syncTransitions:           false,
                    defaultTransitionDuration: 500,
                    onSlideChange:             function(prevIndex, nextIndex) {
                        // 'this' refers to the gallery, which is an extension of $('#thumbs')
                        this.find('ul.thumbs').children()
                            .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
                            .eq(nextIndex).fadeTo('fast', 1.0);
                    },
                    onPageTransitionOut:       function(callback) {
                        this.fadeTo('fast', 0.0, callback);
                    },
                    onPageTransitionIn:        function() {
                        this.fadeTo('fast', 1.0);
                    },
                    onTransitionIn:        function(newSlide, newCaption, isSync) {
                        scale_image();
                        newSlide.fadeTo(this.getDefaultTransitionDuration(isSync), 1.0);
                        if (newCaption)
                            newCaption.fadeTo(this.getDefaultTransitionDuration(isSync), 1.0);
                    }
                });
            });
        </script>
    </body>
</html>

blog/templates/ckeditor/widget.html
<div class="django-ckeditor-widget" data-field-id="{{id}}" style="display: inline-block;">
    <textarea{{ final_attrs|safe }} data-processed="0" data-config='{{config|safe}}' data-external-plugin-resources='{{external_plugin_resources|safe}}' data-id="{{id}}" data-type="ckeditortype">{{ value }}</textarea>
</div>

blog/templates/index/home.html
<html>
<head>
    <meta charset="">
    <title>A simple blog</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta  >
    <meta name="apple-mobile-web-app-status-bar-style" content="white">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="static/css/font.css"/>
    <link rel="stylesheet" href="static/css/transition.css"/>
    <link rel="stylesheet" href="static/css/animate.css"/>
    <link rel="stylesheet" href="static/css/main.css"/>
    <link href="static/ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/zenburn.css" rel="stylesheet">
    
</head>
<body>

<header>
    <h1 class="logo"><span>A Simple </span><span>BLOG</span></h1>
    <nav>
        <ul>
            <li class="on">HOME</li>
            <li>canvas lab</li>
            <li>About</li>
            <!-- <li>Join Us</li> -->
            <li>python</li>
        </ul>
    </nav>
</header>

<div id="pt-main" class="pt-perspective">
    <div class="nav-toggle">
        <span></span>
    </div>
    <canvas id="sphere-bg"></canvas>
    <section id="open" class="pt-page">

        <p class="animated" data-animation="fadeIn">
        <h1>『POWER BY DJANGO』</h1>
        <span>- A SIMPLELY BLOG</span>
        </p>
        <div class="btn-group animated" data-animation="fadeIn">
            <a class="btn btn-github" href="https://github.com/baoziv587" target="_blank">
                <i></i>
                Follow me  On Github
            </a>
            <span class="btn btn-start">
                <i></i>
                Follow me on Weibo
            </span>
        </div>
    </section>
    
    <section id="lab" class="pt-page">
        <h2 class="animated" data-animation="zoomIn">Write the code and <span><strong>Rock</strong> the world</span></h2>
        <ul class="showcase">
            <li>
                <a target="_blank" href="http://labs.music.baidu.com/demo/interactions/visualization/">
                    <div class="thumb" style="background-image: url(img/labs/music_is_life.jpg)"></div>
                    <div class="info">
                        <p class="title">律动的音符</p>
                    </div>
                </a>
            </li>
            <li>
                <a target="_blank" href="http://labs.music.baidu.com/flee/">
                    <div class="thumb" style="background-image: url(img/labs/flee.jpg)"></div>
                    <div class="info">
                        <p class="title">逃逸游戏</p>
                    </div>
                </a>
            </li>
        </ul>
    </section>

    
    
    <section id="about" class="pt-page">
        <h2 class="animated" data-animation="zoomIn"><strong>我是</strong>高翔</h2>
            
                
    </section>
    <section id="weekly" class="pt-page">
        <h2 class="animated" data-animation="zoomIn">NOT FOO AND BAR<br> ONLY FUCK AND SHIT</h2>
        {% block content %}
      <div class="content" style="margin:0 auto;">        
          <ul>
            {%for blog in blogs%}
            <li><a href="blog/{{blog.id}}"><h5>{{blog.title}}</h5></a></li>
            {% endfor%}
          </ul>         
      </div>
  {% endblock %}
        
    </section>
</div>

<footer>
    <ul class="social">
        <li class="weibo"><a href="http://weibo.com/musicfe" target="_blank"></a></li>
        <li class="github"><a href="https://github.com/Baidu-Music-FE" target="_blank"></a></li>
    </ul>
    <p class="copyright">&copy;2015</p>
</footer>

<script src="static/js/jquery.min.js"></script>
<script src="static/js/lodash.min.js"></script>
<script src="static/js/ys-sphere.js"></script>
<script src="static/js/main.js"></script>
<script src="static/ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>